# Lab 4.08 - Off days

*(This exercise was generated by <https://rlanders.net/dataset-generator/>)*

In [18]:
# Package imports for data science
import numpy as np
import pandas as pd
import scipy.stats as stats
from pandas.api.types import CategoricalDtype
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.graphics.mosaicplot import mosaic


You run a small business with four employees: Susan, Jimmy, Albert, and Camilla. Because you need three employees at work at any given time, only one employee ever has the day off. Unfortunately, everyone always wants Saturday off. One of your employees has confronted you and said that you favor some employees over others in providing Saturdays off. To investigate this, you pulled up a list of who has recently had Saturdays off each week (see `data/off-days.csv`).

Visualize the data and conduct a suitable statistical test to investigate this. Complete the full hypothesis testing process and draw all appropriate conclusions.

In [19]:
df = pd.read_csv("../data/off-days.csv")
df.head()

  EmployeeName
0        Susan
1       Albert
2      Camilla
3       Albert
4        Susan

In [20]:
total_saturdays = len(df)
by_employee = df['EmployeeName'].value_counts().reset_index()
by_employee['expected'] = total_saturdays / len(by_employee)
by_employee.head()

  EmployeeName  count  expected
0        Susan     48      30.0
1       Albert     42      30.0
2      Camilla     24      30.0
3        Jimmy      6      30.0

In [21]:
H0 = 'There is insufficient evidence to say that any employee received preferential treatment.'
H1 = 'There is enough evidence to say that at least one employee received preferential treatment.'

chi2, p_value = stats.chisquare(f_obs=by_employee['count'], f_exp=by_employee['expected'])
print(f"Chi2 = {chi2}\np = {p_value}")
print(H0 if p_value > 0.05 else H1)

Chi2 = 36.0
p = 7.488376948795475e-08
There is enough evidence to say that at least one employee received preferential treatment.

In [28]:
expected_p = 1 / len(by_employee) # elke employee heeft even veel kans
by_employee['preference'] = (by_employee['count'] - by_employee['expected']) / np.sqrt(by_employee['count'] * (1 - by_employee['expected_p']))

print("Susan and Albert got preferential treatment, while Jimmy is not treated fairly. Camilla's off-days are on the low side, but still realistic.")
by_employee.head()

Susan and Albert got preferential treatment, while Jimmy is not treated fairly. Camilla's off-days are on the low side, but still realistic.

  EmployeeName  count  expected  expected_p  preference
0        Susan     48      30.0        0.25    3.000000
1       Albert     42      30.0        0.25    2.138090
2      Camilla     24      30.0        0.25   -1.414214
3        Jimmy      6      30.0        0.25  -11.313708