## Example Exam Questions Chapter 4

In [165]:
# Package imports for data science
import numpy as np
import pandas as pd
import scipy.stats as stats
from pandas.api.types import CategoricalDtype
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.graphics.mosaicplot import mosaic

## Exercise 1
Criminologists have long debated whether there is a relationship between weather conditions and the number of crimes committed. In 1988, an article “Is there a
Season for Homicide?” (Criminology, 1988: 287-296) classified 1361 homicides by season, resulting
in the data below.  
Is there an association between season and the number of murders committed?

In [166]:
dfmurders = pd.DataFrame(data={
    'season': ['winter', 'spring','summer','autumn'],
    'number_of_murders': [328, 334, 372, 327]
})

In [167]:
H0 = 'There is insufficient evidence to suspect that seasons influence the number of murders committed.'
H1 = 'There is enough evidence to conclude that seasons influence the number of murders committed.'

dfmurders['expected'] = dfmurders['number_of_murders'].sum() / len(dfmurders['season'])
dfmurders.head()

   season  number_of_murders  expected
0  winter                328    340.25
1  spring                334    340.25
2  summer                372    340.25
3  autumn                327    340.25

In [168]:
alpha = 0.05
chi2, p_value = stats.chisquare(f_obs=dfmurders['number_of_murders'], f_exp=dfmurders['expected'])
print(f'Chi2 = {chi2}\np = {p_value}')
print(H0 if p_value > alpha else H1)

Chi2 = 4.034533431300514
p = 0.25775920748891007
There is insufficient evidence to suspect that seasons influence the number of murders committed.

## Exercise 2
A random sample of individuals was taken, and each individual was classified according to their level of education and their sense of spirituality.
Is there an association between the level of education and the sense of spirituality?

In [169]:
dfspirituality = pd.DataFrame(data={
    'sense_of_spirituality': ['lot', 'moderate','little','none'],
    'alfa_scientist': [56, 162, 198, 211],
    'beta_scientist': [56, 223, 243, 239],
    'not_scientist': [109, 164, 74, 28]
})
dfspirituality.head()

  sense_of_spirituality  alfa_scientist  beta_scientist  not_scientist
0                   lot              56              56            109
1              moderate             162             223            164
2                little             198             243             74
3                  none             211             239             28

In [170]:
dfspirituality = dfspirituality.set_index('sense_of_spirituality')
dfspirituality['total'] = dfspirituality.sum(axis=1)
dfspirituality.loc['total'] = dfspirituality.sum()
dfspirituality.head()

                       alfa_scientist  beta_scientist  not_scientist  total
sense_of_spirituality
lot                                56              56            109    221
moderate                          162             223            164    549
little                            198             243             74    515
none                              211             239             28    478
total                             627             761            375   1763

In [171]:
chi2, p_value, dof, expected = stats.chi2_contingency(dfspirituality)
print(f'Chi2 = {chi2}\np_value = {p_value}')
alpha = 0.05
print("There is not enough evidence to say that spirituality and level of education are dependent" if p_value > alpha else "The sample suggests there is a level of dependence between spirituality and level of education")

Chi2 = 213.21219825787216
p_value = 6.052636926984847e-39
The sample suggests there is a level of dependence between spirituality and level of education

## Exercise 4

In an experiment, 150 patients were divided into three groups of 45, 45 and 60 patients each. Two groups were given a new drug in different doses and the third group was given a placebo. The way the patients felt after using the drug are shown in the data frame below. Is there evidence at the 5% significance level that there is a difference in the condition between the three groups of patients?

In [172]:
dfexperiment = pd.DataFrame(data={
    'state': ['better', 'equal', 'worse'],
    'placebo': [16, 20, 9],
    'half_dosis': [17, 18, 10],
    'full_dosis': [26, 20, 14]
}).set_index('state')
dfexperiment.head()

        placebo  half_dosis  full_dosis
state
better       16          17          26
equal        20          18          20
worse         9          10          14

In [173]:
dfexperiment['total'] = dfexperiment.sum(axis=1)
dfexperiment.loc['total'] = dfexperiment.sum()
dfexperiment.head()

        placebo  half_dosis  full_dosis  total
state
better       16          17          26     59
equal        20          18          20     58
worse         9          10          14     33
total        45          45          60    150

In [174]:
chi2, p_value, dof, expected = stats.chi2_contingency(dfexperiment)
print(f"Chi2 = {chi2}\np = {p_value}")

Chi2 = 1.41691609254438
p = 0.9977174743301471

In [175]:
alpha = 0.05
print("There is not enough evidence to suggest that the dosis and the patients felt after the experiment are dependent." if p_value > alpha else "There is sufficient evidence to suggest that the dosis had an effect on the way people felt")

There is not enough evidence to suggest that the dosis and the patients felt after the experiment are dependent.